#This is an example YAML for upgrading jiva volume.
#Some of the values below needs to be changed to
#match your openebs installation. The fields are
#indicated with VERIFY
---
apiVersion: batch/v1
kind: Job
metadata:
  #VERIFY that you have provided a unique name for this upgrade job.
  #The name can be any valid K8s string for name. This example uses
  #the following convention: jiva-vol-<flattened-from-to-versions>
  name: jiva-vol-1120210

  #VERIFY the value of namespace is same as the namespace where openebs components
  # are installed. You can verify using the command:
  # `kubectl get pods -n <openebs-namespace> -l openebs.io/component-name=maya-apiserver`
  # The above command should return status of the openebs-apiserver.
  namespace: openebs

spec:
  backoffLimit: 4
  template:
    spec:
      # VERIFY the value of serviceAccountName is pointing to service account
      # created within openebs namespace. Use the non-default account.
      # by running `kubectl get sa -n <openebs-namespace>`
      serviceAccountName: openebs-maya-operator
      containers:
        - name:  upgrade
          args:
            - "jiva-volume"

            # --from-version is the current version of the volume
            - "--from-version=1.12.0"

            # --to-version is the version desired upgrade version
            - "--to-version=2.2.0"

            # Bulk upgrade is supported
            # To make use of it, please provide the list of PVs
            # as mentioned below
            - "pvc-1bc3b45a-3023-4a8e-a94b-b457cf9529b4"
            - "pvc-82a2d097-c666-4f29-820d-6b7e41541c11"

            #Following are optional parameters
            #Log Level
            - "--v=4"
          #DO NOT CHANGE BELOW PARAMETERS
          env:
            - name: OPENEBS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          tty: true

          # the image version should be same as the --to-version mentioned above
          # in the args of the job
          image: openebs/m-upgrade:2.2.0
          imagePullPolicy: Always
      restartPolicy: OnFailure
---